### ISSUE TITLE
brew announce doesn't render emoji in iTerm2 ?

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-linux-dev#80]
I am using `iTerm2 Build 3.1.5`.  
```
brew announce samblaster
==> brewsci/bio/samblaster
 New formula samblaster in Brewsci/bio for Linux and macOS!
ℹ️ Fast duplicate marking in SAM files
 brew install brewsci/bio/samblaster
 https://github.com/GregoryFaust/samblaster
 https://doi.org/10.1093/bioinformatics/btu314
 https://github.com/brewsci/homebrew-bio
 http://linuxbrew.sh @linuxbrew #bioinformatics
```
Do i need to change my terminal type or code page etc etc ?

```
    puts <<~EOS
      <U+1F389> New formula #{formula.name} in #{formula.tap.name.capitalize} for #{os}!
      ℹ️ #{formula.desc}
      <U+1F37A> brew install #{formula.full_name}
      <U+1F3E1> #{formula.homepage}
    EOS
    puts "<U+1F4D6> #{cite}" if cite
    puts <<~EOS
      <U+1F52C> #{formula.tap.remote}
      <U+1F427> http://linuxbrew.sh @linuxbrew #bioinformatics
    EOS
```
![image](https://user-images.githubusercontent.com/453972/37940698-cfc9e578-31b5-11e8-819c-74006878177f.png)

```
locale
LANG=en_AU.UTF-8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
```

**Comment by sjackman** [comment]
Those hex `U+1Fxxx` codes all look correct. Does it work in macOS Terminal? Which version of macOS are you using? It works for me on El Capitan and High Sierra with macOS Terminal, and it worked for @jonchang just now.

**Comment by sjackman** [comment]
Did your previous shell version of this script work, and this new Ruby version does not work?

**Comment by sjackman** [comment]
Jon had a good suggestion.
```
brew announce samblaster | pbcopy
```
then paste into GitHub.

**Comment by jonchang** [comment]
Yeah no clue, it might be a font selection thing or something. It works fine with default Terminal for me. Does the iterm2 bug tracker have any clues?

**Comment by sjackman** [comment]
Ah, good suggestion about the font. Try a system font like Monaco

**Comment by tseemann** [comment]
On iTerm2 it is using Monaco:

![image](https://user-images.githubusercontent.com/453972/38008644-81efb3b4-329b-11e8-8d4f-c22b8cb92a34.png)

Interestingly, if I use regular Terminal it works.

🔬 https://github.com/brewsci/homebrew-bio
🐧 http://linuxbrew.sh @linuxbrew #bioinformatics

It's using `Menlo Regular` font by default and Unicode UTF-8.  

WEIRD.

**Comment by rohni** [comment]
@tseemann I have been wrestling with this for a bit now as well.  Taking a hint that Terminal shows emoji correctly, I had a look through it settings and found the:
"Set locale environment variables on startup" setting was checked.

Thought I'd have a look in the iTerm2 settings and found that it had a similar setting.  Once I put it on, emojis started showing up properly. 
iTerm Preferences -> Profiles -> Terminal -> Environment -> Set locale variables automatically
![screen shot 2018-05-07 at 14 03 23](https://user-images.githubusercontent.com/839216/39701367-30ad08b4-5201-11e8-98ab-f71d6f144da5.png)

Hope this helps, I know it solved the problem for me.
